### ISSUE TITLE
Implement one DELETE and one UPDATE function in your website

### ISSUE THREAD

**Issue by mbaiza27** [mbaiza27/CS340SMITEProject#3]
This is a specific requirement from the project. This is going to be tough for our project because it wouldn't make that much since for the user to DELETE and UPDATE gods, items, types, classes, etc. My only idea for this requirement is something like a "My Builds" page where somebody can create a build with 6 items and save it, delete it, or update it. That's all we really need for this requirement.

**Comment by Solid-Snek** [comment]
I like that idea, having user builds is a cool idea. 
Another idea, if you want something else to consider is a sort of "favorites" that a user can maintain. You could choose a favorite role (this is where we could have a user update their favorite role) and choose favorite gods (this could be the delete/insert).

Either one is fine, just thought I'd bring up another idea.

**Comment by Solid-Snek** [comment]
If we don't want to add extra tables or do anything to our plan, creating a build could totally work.
